[package]
name = "windows_audio"
version = "0.1.3"
edition = "2021"
authors = ["https://twitter.com/8bitTD", "8bittd@gmail.com"]
repository = "https://github.com/8bitTD/windows_audio"
keywords = ["windows", "audio", "wav"]
license = "MIT"
readme = "README.md"
description = "Sounds a wav file that can be used by default on windowsOS"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.16.0"